version: '3'
services:

  postfix:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "25:25"
    volumes:
      - ./mails:/usr/src/app/mails


volumes:
  storage:
    driver: local
